// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

=== Test the deployment

==== Copy the database secret ARN from Secrets Manager
. Sign in to the AWS Management Console and open the https://console.aws.amazon.com/secretsmanager/[Secrets Manager console].
. In the left navigation pane, choose *Secrets*.
. Choose the secret for your deployment, either `/graphqlrdsserverless/dbsecret` (Aurora Serverless v.1) or `/graphqlrds/dbsecret` (Aurora PostgreSQL-compatible).
. On the secret details page, copy the *Secret ARN*.

==== Run a SQL query to test the database
. Open the https://console.aws.amazon.com/rds/[Amazon RDS console].
. In the left navigation pane, choose *Query Editor*.
. For *Database instance or cluster*, choose your database cluster.
. For *Database username*, choose *Connect with a Secrets Manager ARN*.
. Enter the database secret ARN that you copy from Secrets Manager. Refer to link:#_copy_the_database_secret_arn_from_secrets_manager[Copy the database ARN from Secrets Manager], earlier in this guide.
. For *Enter the name of the database*, enter `graphqlrds`.
. In the query editor, enter the following statement.

+
[source,sql]
....
SELECT * FROM graphqlsample.my_order WHERE order_id = 'ORD-100';
....

[start=8]
. Choose *Run* and the query editor displays the results.

==== Run a GraphQL query to test the AppSync API
. Open the https://console.aws.amazon.com/appsync/[AWS AppSync console].
. In the left navigation pane, choose APIs.
. Choose the deployment GraphQL API.
. In the left navigation pane, choose *Queries*.
. On the *Queries* page, enter the following query code. The code provided runs a GraphQL query identical to the previous link:#_run_a_sql_to_test_the_database[SQL query].

+
[source,asciidoc]
....
query MyQuery {
  graphqlsample_MyOrder(where: {OrderId: {eq: "ORD-100"}}) {
    edges {
      node {
        OrderDate
        SourceIpAddress
        CustomerId
        Status
        TotalCost
      }
    }
  }
}
....

[start=6]
. Choose the play button to run the query. The query editor displays the results in the right pane. Your results should match the following example.

+
[source,asciidoc]
....
{
  "data": {
    "graphqlsample_MyOrder": {
      "edges": [
        {
          "node": {
            "OrderDate": "2022-09-13T10:10:01Z",
            "SourceIpAddress": "169.114.197.175",
            "CustomerId": "CUST-3675",
            "Status": "Placed",
            "TotalCost": 500.55
          }
        }
      ]
    }
  }
}
....

NOTE: Because a new Lambda function must be created and initialized, the query may take a minute or so to display the results.

When you get more familiar with AppSync, you can use the AppSync query explorer to create similar queries.

==== Test the API Key
Test the API key and `auth` functionality by running a query from the command line to simulate a Salesforce HTTP call to AppSync. You can use the `curl` command or Postman. The following example that you can copy uses the `curl` command.
[source,asciidoc]
....
curl -XPOST -H "Content-Type:application/graphql" -H "x-api-key:YOUR-API-key" -d '{ "query": "query MyQuery {graphqlsample_MyOrder(where: {OrderId: {eq: \"ORD-100\"}}) {edges {node {OrderDate SourceIpAddress CustomerId Status TotalCost}}}}" }' https://YOUR-APPSYNC-ENDPOINT/graphql
....

Your results should match the following, which are formatted for readability.
[source,asciidoc]
....
{
  "data": {
    "graphqlsample_MyOrder": {
      "edges": [
        {
          "node": {
            "OrderDate": "2022-09-13T10:10:01Z",
            "SourceIpAddress": "169.114.197.175",
            "CustomerId": "CUST-3675",
            "Status": "Placed",
            "TotalCost": 500.55
          }
        }
      ]
    }
  }
}
....

=== Salesforce configuration

==== Load sample data into Salesforce

Use the solution’s sample data (`sample-customers.csv`) to test the connection between Salesforce and AWS AppSync. The sample data simulates a scenario in which customer data is stored in Salesforce and order and product data is stored in Amazon Relational Database Service (Amazon RDS). The order table has a foreign key identifying the customer who placed the order. If this natural key can also be found in Salesforce, it can be used to create an indirect lookup that links orders to accounts.

. Sign in to your Salesforce org.
. Create a text field on the `customerID` account object. Ensure that you mark the text field as an external ID and unique.
. Import `sample-customers.csv` as accounts and contacts using the https://trailhead.salesforce.com/content/learn/projects/import-and-export-with-data-management-tools/use-the-data-import-wizard[Data Import Wizard]. Ensure that you import the first column of `sample-customers.csv` into the new `customerID` field you create in step 2.

After you connect Salesforce to AWS AppSync, the data from the external system appears as a related list on the Salesforce account page.

==== Configure the named credential

Configure a https://help.salesforce.com/s/articleView?id=sf.graphQL_named_credentials_external_credentials.htm&type=5[Salesforce named credential] so that Salesforce can invoke AWS services.

==== Configure the external data source

Configure an https://help.salesforce.com/s/articleView?id=sf.graphQL_add_external_data_source.htm&type=5[external data source] for the AppSync API and use the exposed metadata to help create https://help.salesforce.com/s/articleView?id=sf.graphQL_sync_external_data_source.htm&type=5[Salesforce external objects]. For more information, refer to https://help.salesforce.com/s/articleView?id=sf.salesforce_connect_graphQL.htm&type=5[Access External Data with the Salesforce Connect Adapter for GraphQL].

==== Make the data appear in Salesforce

Now that Salesforce has access to the external data, you can make it appear to your Salesforce end users. For the purposes of this test, edit the *Customer ID* field on the new Order object and click Change Field Type to make it an Indirect Lookup to the Account field linked via the *Customer ID* field you added to that standard object.

Once you add the Related List for Orders to the Page Layout for Account, you’ll be able to see the order data from AWS in the context of the customer. This provides a convenient view of a customer's recent orders for support agents and sellers working in Salesforce.

==== Attach your own database table

Once you’ve gotten the out-of-box demo working, you can think about how to surface your own RDS tables to AppSync and Salesforce.

If the tables are in the same RDS instance, you only need to do the following:

* Update the Schema in AppSync by adding the `type` and `input` declarations for the additional table
** Follow the pattern you see in the `Graphqlsample_MyOrder` type to get the syntax correct.
* Make sure to click *Save Schema* to capture your updates.
* Attach the included resolver to the query and mutations for the new table.
** In the *Resolvers* section of the Schema tab in AWS AppSync console, select the query or mutation, and click *Attach*. In *Create new resolver*, select the Lambda function from the dropdown list.
** Repeat the process to attach the resolver for all the queries and mutations defined in the GraphQL schema. For example, if Salesforce Connect can perform create, read, update and delete operations on records, you must attach the resolver four times.
* Add additional entries in the Parameter Store in Systems Manager to specify the metadata.
** Follow the example in `/appsync/typemetadata/Graphqlsample_MyOrder` and create an additional parameter for each table, including the `fieldTypes`, `keyColumns`, etc.

If you are using a different RDS instance, you’ll also need to add the RDS credentials to the Secrets Manager and set up the port forwarding so that the resolver can have a persistent connection to RDS. If you are unsure about this element of the infrastructure, contact AWS support.

After the new GraphQL type is successfully added to the API endpoint (which you should validate with `curl`), you’ll need to go back to your External Data Source definition in Salesforce and Sync the metadata so that Salesforce Connect can pull in the new object(s) and fields. From there, you can decide where exactly to surface this data in the Salesforce UI.
