// Include any postdeployment steps here, such as steps necessary to test that the deployment was successful. If there are no postdeployment steps, leave this file empty.

== Postdeployment steps

=== Test the deployment

==== Copy the database secret ARN from Secrets Manager
. Sign in to the AWS Management Console and open the https://console.aws.amazon.com/secretsmanager/[Secrets Manager console^].
. In the left navigation pane, choose *Secrets*.
. Choose the secret for your deployment, either `/graphqlrdsserverless/dbsecret` (Aurora Serverless v.1) or `/graphqlrds/dbsecret` (Aurora PostgreSQL-compatible).
. On the secret details page, copy the *Secret ARN*.

==== Run a SQL query to test the database
. Open the https://console.aws.amazon.com/rds/[Amazon RDS console^].
. In the left navigation pane, choose *Query Editor*.
. For *Database instance or cluster*, choose your database cluster.
. For *Database username*, choose *Connect with a Secrets Manager ARN*.
. Enter the database secret ARN that you copy from Secrets Manager. Refer to link:#_copy_the_database_secret_arn_from_secrets_manager[Copy the database ARN from Secrets Manager], earlier in this guide.
. For *Enter the name of the database*, enter `graphqlrds`.
. In the query editor, enter the following statement.

+
[source,sql]
....
SELECT * FROM graphqlsample.my_order WHERE order_id = 'ORD-100';
....

[start=8]
. Choose *Run* and the query editor displays the results.

==== Run a GraphQL query to test the AppSync API
. Open the https://console.aws.amazon.com/appsync/[AWS AppSync console^].
. In the left navigation pane, choose APIs.
. Choose the deployment GraphQL API.
. In the left navigation pane, choose *Queries*.
. On the *Queries* page, enter the following query code. The code provided runs a GraphQL query identical to the previous link:#_run_a_sql_to_test_the_database[SQL query].

+
[source,asciidoc]
....
query MyQuery {
  graphqlsample_MyOrder(where: {OrderId: {eq: "ORD-100"}}) {
    edges {
      node {
        OrderDate
        SourceIpAddress
        CustomerId
        Status
        TotalCost
      }
    }
  }
}
....

[start=6]
. Choose the play button to run the query. The query editor displays the results in the right pane. Your results should match the following example.

+
[source,asciidoc]
....
{
  "data": {
    "graphqlsample_MyOrder": {
      "edges": [
        {
          "node": {
            "OrderDate": "2022-09-13T10:10:01Z",
            "SourceIpAddress": "169.114.197.175",
            "CustomerId": "CUST-3675",
            "Status": "Placed",
            "TotalCost": 500.55
          }
        }
      ]
    }
  }
}
....

NOTE: Because a new Lambda function must be created and initialized, the query may take a minute or so to display the results.

When you get more familiar with AppSync, you can use the AppSync query explorer to create similar queries.

==== Test the API Key
Test the API key and `auth` functionality by running a query from the command line to simulate a Salesforce HTTP call to AppSync. You can use the `curl` command or Postman. The following example that you can copy uses the `curl` command.
[source,asciidoc]
....
curl -XPOST -H "Content-Type:application/graphql" -H "x-api-key:YOUR-API-key" -d '{ "query": "query MyQuery {graphqlsample_MyOrder(where: {OrderId: {eq: \"ORD-100\"}}) {edges {node {OrderDate SourceIpAddress CustomerId Status TotalCost}}}}" }' https://YOUR-APPSYNC-ENDPOINT/graphql
....

Your results should match the following, which are formatted for readability.
[source,asciidoc]
....
{
  "data": {
    "graphqlsample_MyOrder": {
      "edges": [
        {
          "node": {
            "OrderDate": "2022-09-13T10:10:01Z",
            "SourceIpAddress": "169.114.197.175",
            "CustomerId": "CUST-3675",
            "Status": "Placed",
            "TotalCost": 500.55
          }
        }
      ]
    }
  }
}
....

=== Salesforce configuration tutorial

Complete the following tutorial to learn how to configure Salesforce to view and interact with external data without copying or storing them. Using a sample data set, these instructions demonstrate how to augment Salesforce customer data with order data stored externally.

//Use the sample data provided with the solution to demonstrate how to augment Salesforce customer data with order data stored in an external database. The sample data simulates a scenario in which customer data is stored in Salesforce and order and product data is stored in Amazon Relational Database Service (Amazon RDS).

//This provides a convenient view of a customer's recent orders for support agents and sellers working in Salesforce.

. Create a sample data file containing the following fields:
`customer_id`, `customer_name`, `type`, `industry`, `phone`, `address`, `city`, `state`, `zip`, `contact_first_name`, `contact_last_name`, `contact_email`, `contact_phone`, and `contact_title`.

+
NOTE: You can generate mock data and save them as a CSV file using https://www.mockaroo.com/[Mockaroo^].

. Sign in to your Salesforce org.
. Create a text field in the standard customerID account object. In *General Options*, ensure that you choose the *Unique* and *External ID* settings.
. Use the Salesforce Data Import Wizard to import your sample data.
.. For *What kind of data are you importing?*, choose *Accounts and Contacts*.
.. Ensure that you import the first column of your file (`customer_id`) into the new `customerID` field you create in the previous step. For more information, refer to https://trailhead.salesforce.com/content/learn/projects/import-and-export-with-data-management-tools/use-the-data-import-wizard[Use the Data Import Wizard^].
. Configure a https://help.salesforce.com/s/articleView?id=sf.graphQL_named_credentials_external_credentials.htm&type=5[Salesforce named credential^] so that Salesforce can invoke AWS services.
. Configure an https://help.salesforce.com/s/articleView?id=sf.graphQL_add_external_data_source.htm&type=5[external data source^] for the AppSync API and use the exposed metadata to help create https://help.salesforce.com/s/articleView?id=sf.graphQL_sync_external_data_source.htm&type=5[Salesforce external objects^]. For more information, refer to https://help.salesforce.com/s/articleView?id=sf.salesforce_connect_graphQL.htm&type=5[Access External Data with the Salesforce Connect Adapter for GraphQL^].
. Edit the *Customer ID* field on the new order object you created in step 6.
.. Change the field type to *Indirect Lookup Relationship*.
.. Configure the field to link to the *Account* field by way of the field you created in the standard `CustomerID` object in step 2. For more information, refer to to https://trailhead.salesforce.com/content/learn/projects/quickstart-lightning-connect/quickstart-lightning-connect3#:~:text=An%20indirect%20lookup%20relationship%20is,links%20standard%20or%20custom%20objects[Create an Indirect Lookup Relationship^].
. After you create an indirect lookup, Salesforce adds a new related list on the *Account* page. To make the order data appear to Salesforce end users, add the related list for orders to the page layout for the account object. For more information, refer to https://help.salesforce.com/s/articleView?id=sf.emergency_response_add_related_lists_page_layout.htm&type=5[Add Related Lists to Page Layouts^].


==== Attach your own database table (in the same RDS DB instance)

After completing the tutorial, you can make your own tables appear to AppSync and Salesforce. If the tables are in the same RDS DB instance, do the following:

* Update the Schema in AppSync by adding the `type` and `input` declarations for the additional table. Follow the pattern you see in the `Graphqlsample_MyOrder` type to get the syntax correct.
* Ensure that you choose *Save Schema* to capture your updates.
* Attach the included resolver to the query and mutations for the new table.
** In the *Resolvers* section of the Schema tab in AWS AppSync console, select the query or mutation, and click *Attach*. In *Create new resolver*, select the Lambda function from the dropdown list.
** Repeat the process to attach the resolver for all the queries and mutations defined in the GraphQL schema. For example, if Salesforce Connect can perform create, read, update and delete operations on records, you must attach the resolver four times.
* Add additional entries in the Parameter Store in Systems Manager to specify the metadata.
** Follow the example in `/appsync/typemetadata/Graphqlsample_MyOrder` and create an additional parameter for each table, including the `fieldTypes`, `keyColumns`, etc.

==== Attach your own database table (in a different RDS instance)
If you are using a different RDS DB instance, add the Amazon RDS credentials to Secrets Manager and set up the port forwarding so that the resolver can have a persistent connection to RDS. If you are unsure about this element of the infrastructure, contact AWS support.

After the new GraphQL type is successfully added to the API endpoint (which you should validate with `curl`), you’ll need to go back to your External Data Source definition in Salesforce and Sync the metadata so that Salesforce Connect can pull in the new object(s) and fields. From there, you can decide where exactly to surface this data in the Salesforce UI.
